from _datetime import datetime, timedelta
current_date = datetime.now()
print(current_date)
print("today's date: ", current_date.date())
print("today's date value: ", current_date.day)
print("Current year: ", current_date.year)
print("current month: ", current_date.month)
date_time_format2 = current_date.strftime("%d_%B_%Y_%H_%M_%S")
print("date time format value :", date_time_format2)
print("2 days ago date: ", (current_date-timedelta(days=2)).date())
print("2 days after date: ", (current_date+timedelta(days=2)).date())