import time

from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(10)
driver.get("https://www.goibibo.com/")
driver.find_element(By.CSS_SELECTOR,"[class='logSprite icClose']").click()
driver.find_element(By.CSS_SELECTOR,"[class='sc-1f95z5i-8 joWRFB header-sprite nav-icon-bus']").click()
input_filed = driver.find_element(By.XPATH,"//input[@name='autosuggestBusSRPSrcHomeName']")
input_filed.click()
input_filed.send_keys("karad")
time.sleep(5)
drop_down = driver.find_element(By.XPATH,"//span[text()='Karad, Maharashtra']")
drop_down.click()
input_filed = driver.find_element(By.ID,"autosuggestBusSRPDestHome")
input_filed.click()
input_filed.send_keys("swargate")
time.sleep(5)
drop_down = driver.find_element(By.XPATH,"//span[text()='Swargate, Pune']")
drop_down.click()
driver.find_element(By.XPATH,"//input[@placeholder='Pick a date']").click()
select_date = driver.find_element(By.XPATH,"//span[text()='3']")
time.sleep(5)
select_date.click()
driver.find_element(By.XPATH,"//span[text()='Tomorrow']").click()
driver.find_element(By.XPATH,"//button[@data-testid='searchBusBtn']").click()
driver.find_element(By.XPATH,"(//*[contains(text(), 'SELECT SEAT')])[1]").click()
driver.find_element(By.XPATH,"//label[.//p[text()='20:10'] and .//p[text()='Balaji Nagar']]").click()
driver.find_element(By.XPATH,"//div[contains(@class,'SeatWithTooltipstyles__BusSeat-sc-dkrka-2 fjDZVL')]").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[text()='CONTINUE']").click()
driver.find_element(By.XPATH,"//span[text()='Add GoAssure At ₹14/person']").click()
driver.find_element(By.XPATH,"//input[@placeholder='Enter Full Name']").send_keys("Rohit Sharma")
driver.find_element(By.XPATH,"//input[@placeholder='Age']").send_keys("34")
driver.find_element(By.XPATH,"//span[text()='Male']").click()
driver.find_element(By.XPATH,"//input[@placeholder='Enter Email Address']").send_keys("Dheeraj12@gmail.com")
driver.find_element(By.XPATH,"//input[@placeholder='Enter Mobile Number']").send_keys('7635272637')
driver.find_element(By.XPATH,"//label[@for='confirm_check']").click()
time.sleep(5)

pay_button = driver.find_element(By.XPATH,"//button[contains(@class,'PayButton')]")
pay_button.click()
time.sleep(10)
driver.close()