import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select

driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(5)
driver.get("https://www.goibibo.com/")
driver.find_element(By.XPATH,"//span[@class='logSprite icClose']").click()
driver.find_element(By.XPATH,"//input[@id='fromCity']").click()
input_field = driver.find_element(By.XPATH,"//input[@placeholder='From']")
input_field.click()
input_field.send_keys("Mumbai")
driver.find_element(By.XPATH,"//li[@id='react-autowhatever-1-section-0-item-0']").click()
driver.find_element(By.ID, "toCity").click()
input_field = driver.find_element(By.XPATH, "//input[@placeholder='To']")
input_field.click()
input_field.send_keys("Goa")
time.sleep(10)
dropdown_parent = driver.find_element(By.XPATH, "//div[@id='react-autowhatever-1']")
dropdown_parent.find_element(By.XPATH, "//p[text()='Goa - Dabolim Airport, India']").click()
time.sleep(10)
driver.find_element(By.XPATH,"//div[@aria-label='Sat Dec 06 2025']").click()
driver.find_element(By.XPATH,"//span[text()='Return']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[@aria-label='Mon Dec 08 2025']").click()
driver.find_element(By.XPATH,"//span[text()='Travellers & Class']").click()
time.sleep(10)
driver.find_element(By.XPATH,"//li[@data-cy='adults-2']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//li[@data-cy='children-1']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//li[@data-cy='infants-2']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//li[@data-cy='travelClass-1']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//button[@type='button']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//div[contains(text(), 'Doctor and Nurses')]").click()
driver.find_element(By.XPATH,"//a[text()='Search']").click()
driver.find_element(By.CSS_SELECTOR,"[class='bgProperties overlayCrossIcon icon20']").click()
time.sleep(10)
driver.close()